Feature Scaling

In [2]:
import pandas as pd
import numpy as np 

#  Sample dataframe 
data =  pd.DataFrame({
  "Height": [150,160,165,180,170],
  "Height": [65,72,78,85,70]
})

In [4]:
data

   Height
0      65
1      72
2      78
3      85
4      70

Standard Scaler

In [8]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import numpy as np 

Standard_scale = StandardScaler()

scaled_data = Standard_scale.fit_transform(data)

scaled_data

array([[-1.30448483],
       [-0.28988552],
       [ 0.57977104],
       [ 1.59437035],
       [-0.57977104]])

In [16]:


scaled_df = pd.DataFrame(
    scaled_data,
    columns=["scaled_height", ]
)

scaled_df

   scaled_height
0      -1.304485
1      -0.289886
2       0.579771
3       1.594370
4      -0.579771